### ISSUE TITLE
Add some thumbnails for blog posts

### ISSUE THREAD

**Issue by edrisranjbar** [edrisranjbar/edrisranjbar.ir#6]

**Comment by akshayjha21** [comment]
hey, i want to work on this issue can u explain it more , what actually u need to edit

**Comment by edrisranjbar** [comment]
Thank you. yes of course; i want to include some images in `assets/images` fro blog posts. these images should be free with no copyright issue. if you can download and put those images in mentioned directory it would be helpful.
